site_name: -nome gioco- Game Bible

theme:
  name: "material"

nav:
  - Indice: index.md
  - Tema e Tetrade: description.md
  - Gameplay:
      - Base di Gameplay: gameplay.md
      - Meccaniche del Giocatore: mechanics.md
  - Bibliografia: bibliography.md
