site_name: Nostos Game Bible

theme:
  name: "material"

nav:
  - Il gioco e il Tema: index.md
  - Tetrade: description.md
  - Gameplay:
      - Base di Gameplay: gameplay.md
      - Meccaniche del Giocatore: mechanics.md
  - Livelli: levels.md
  - Bibliografia: bibliography.md