site_name: -nome gioco- Game Bible

theme:
  name: "material"

nav:
  - Indice: index.md
  - Tema e Tetrade: description.md
  - Bibliografia: bibliography.md
  - Personaggi: characters.md
  - Luoghi: locations.md
  - Nemici: enemies.md
  - Boss: bosses.md
